export const ORDER_STATUS = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAID_PENDING_FULFILLMENT: 'PAID_PENDING_FULFILLMENT',
  SUBMITTED_TO_VENDOR: 'SUBMITTED_TO_VENDOR',
  TICKET_ISSUED: 'TICKET_ISSUED',
  TICKET_FAILED: 'TICKET_FAILED',
  REFUND_REVIEWING: 'REFUND_REVIEWING',
  REFUND_PROCESSING: 'REFUND_PROCESSING',
  REFUNDED: 'REFUNDED',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
} as const;

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];
